sudo: required
services:
    - docker
before_install:
    - docker build -t manindra23/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true manindra23/react-test  npm test -- --coverage

after_success:
    - docker build -t manindra23/multi-client ./client
    - docker build -t manindra23/multi-nginx ./nginx
    - docker build -t manindra23/multi-server ./server
    - docker build -t manindra23/multi-worker ./worker
#login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Take those images and push to docker hub
    - docker push manindra23/multi-client
    - docker push manindra23/multi-nginx
    - docker push manindra23/multi-server
    - docker push manindra23/multi-worker

